CREATE TABLE IF NOT EXISTS statistics
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app_id   BIGINT                                  NOT NULL,
    uri      VARCHAR(512)                            NOT NULL,
    ip       VARCHAR(512)                            NOT NULL,
    hit_date TIMESTAMP                               NOT NULL,
    CONSTRAINT pk_stats PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS applications
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app_name VARCHAR(200),
    CONSTRAINT pk_applications PRIMARY KEY (id),
    CONSTRAINT UQ_APP_NAME UNIQUE (app_name)
)