CREATE TABLE IF NOT EXISTS statistics
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app      VARCHAR(255)                            NOT NULL,
    uri      VARCHAR(512)                            NOT NULL,
    ip       VARCHAR(512)                            NOT NULL,
    hit_date TIMESTAMP                               NOT NULL,
    CONSTRAINT pk_stats PRIMARY KEY (id)
);